# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6484159eb6259537938428c68564835b135c7273d39b6c0eceba636d61d06856aff25516c63f335089a3c1ba6c627965968760173120f144c2121096472d081f

test:
  secret_key_base: c5b716a2cd489cd1240c9cd086ca51660bf4b66c68622a091db275e3bfa8bc1173ee1788b601b2507af6cca9c3c2b87a2ffc1ca8a9872cba3f4452d1c118af11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
